app:
  version: @project.version@
  build-time: @build.timestamp@
  security:
    header-string: "Authorization"
    token-prefix: "Bearer "
    jwt-ttl: 2
    jwt-ttl-unit: hours

spring:
  profiles:
    active: config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver