app:
  admin:
#    username: admin # Username of administrator
#    password: admin # Default password of administrator
#    nick-name: Administrator # Nickname of administrator
#    email: admin@fatweb.top # Email of administrator
  security:
#    header-string: "Authorization" # The key of head to get token
#    token-prefix: "Bearer " # Token prefix
#    jwt-ttl: 2 # The life of token
#    jwt-ttl-unit: hours # Unit of life of token [nanoseconds, microseconds, milliseconds, seconds, minutes, hours, days]
    jwt-key: $uuid$ # Key to generate token (Only numbers and letters allow)
#    jwt-issuer: FatWeb # Token issuer
#    redis-ttl: 20 # The life of token in redis
#    redis-ttl-unit: minutes # Unit of life of token in redis [nanoseconds, microseconds, milliseconds, seconds, minutes, hours, days]

server:
#  port: 8080 # Server port

spring:
  datasource:
    url: jdbc:mysql://localhost # MySQL url
    username: root # MySQL username
    password: root # MySQL password
    hikari:
#      pool-name: HikariCP # Connection pool name
#      minimum-idle: 5 # Minimum number of connection in pool
#      idle-timeout: 600000 # The lifetime of connection when idle
#      maximum-pool-size: 10 # Maximum number of connection in pool
#      auto-commit: true # Auto commit
#      max-lifetime: 1800000 # Maximum lifetime of connection
#      connection-timeout: 30000 # Connection timeout
#      connection-test-query: select 1 # Test query then connect


  data:
    redis:
#      database: 0 # Redis database (default: 0)
#      host: localhost # Redis host (default: localhost)
#      port: 6379 # Redis port (default: 6379)
#      password:  # Password of redis
#      connect-timeout: 3000 # Redis connect timeout
#      lettuce:
#        pool:
#          min-idle: 0
#          max-idle: 8
#          max-active: 8
#          max-wait: -1ms

logging:
  level:
    root: info # Logging level
  file:
    name: data/log/fat-api.log # Logging path and name
  logback:
    rollingpolicy:
#      max-file-size: 10MB # Maximum log file size
#      max-history: 7 # Maximum number of archive log files to keep