app:
  version: @project.version@
  build-time: @build.timestamp@

spring:
  profiles:
    active: config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    time-zone: GMT

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: id
      id-type: assign_id
  type-aliases-package: top.fatweb.api.entity

logging:
  level:
    root: info
  file:
    name: data/log/fat-api.log
